#!/usr/bin/env python3
"""
Plot Lagrange Basis Functions from CSV Test Output

This script reads CSV files generated by IPPL's FEM tests and creates plots
showing all basis functions on the reference element with DOF points marked.
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import os
import glob

def plot_1d_basis_functions(csv_file, order):
    """Plot 1D basis functions from CSV file."""
    # Read CSV data
    data = pd.read_csv(csv_file)
    
    # Get x coordinates and basis function columns (all columns except x)
    x = data['x'].values
    basis_cols = [col for col in data.columns if col != 'x']
    
    plt.figure(figsize=(10, 6))
    
    # Define colors for different basis functions
    if len(basis_cols) <= 10:
        colors = plt.cm.tab10(np.linspace(0, 1, len(basis_cols)))
    else:
        colors = plt.cm.tab20(np.linspace(0, 1, len(basis_cols)))
    
    # Plot each basis function
    for i, col in enumerate(basis_cols):
        y = data[col].values
        plt.plot(x, y, label=f'$b^{{{i}}}(x)$', color=colors[i], linewidth=2)
        
        # Find peak location for verification
        max_idx = np.argmax(y)
        peak_x = x[max_idx]
        # Place DOF at correct position: b0 at 0.0, b1 at 1.0, b2-bN at (i-1) * (1/order)
        if i == 0:
            dof_x = 0.0
        elif i == 1:
            dof_x = 1.0
        else:
            dof_x = (i - 1) * (1.0/order)
        plt.plot(dof_x, 1.0, 'o', color=colors[i], markersize=8, markeredgecolor='black')
        plt.plot(dof_x, 0.0, 'o', color=colors[i], markersize=8, markeredgecolor='black')
    
    plt.xlabel('x', fontsize=18)
    plt.ylabel('Basis Function Value', fontsize=18)
    #plt.title(f'1D Lagrange Basis Functions (Order {order})', fontsize=14)
    plt.tick_params(axis='both', labelsize=16)
    plt.legend(fontsize=18, bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    
    # Save plot
    output_file = f'1D_lagrange_basis_order_{order}_plot.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved: {output_file}")

def plot_2d_basis_functions(csv_file, order):
    """Plot 2D basis functions from CSV file."""
    # Read CSV data
    data = pd.read_csv(csv_file)
    
    # Get coordinates and basis function columns (all columns except x, y)
    x = data['x'].values
    y = data['y'].values
    basis_cols = [col for col in data.columns if col not in ['x', 'y']]
    
    # Determine grid size (assuming square grid)
    unique_x = np.unique(x)
    unique_y = np.unique(y)
    nx, ny = len(unique_x), len(unique_y)
    
    # Reshape coordinates to grid
    X = x.reshape(ny, nx)
    Y = y.reshape(ny, nx)
    
    # Create subplots for each basis function
    n_funcs = len(basis_cols)
    cols = int(np.ceil(np.sqrt(n_funcs)))
    rows = int(np.ceil(n_funcs / cols))
    
    fig, axes = plt.subplots(rows, cols, figsize=(4*cols, 4*rows), subplot_kw={'projection': '3d'})
    if n_funcs == 1:
        axes = [axes]
    else:
        axes = axes.flatten()
    
    # Define colors
    if n_funcs <= 10:
        colors = plt.cm.tab10(np.linspace(0, 1, n_funcs))
    else:
        colors = plt.cm.tab20(np.linspace(0, 1, n_funcs))
    
    for i, col in enumerate(basis_cols):
        z_vals = data[col].values.reshape(ny, nx)
        
        ax = axes[i]
        
        # Create surface plot
        surf = ax.plot_surface(X, Y, z_vals, cmap='viridis', alpha=0.8, 
                              edgecolor='none', linewidth=0)
        
        # Find peak location for verification
        max_idx = np.argmax(z_vals)
        max_row, max_col = np.unravel_index(max_idx, z_vals.shape)
        peak_x = X[max_row, max_col]
        peak_y = Y[max_row, max_col]
        # Place DOF at correct position based on 2D numbering
        if i == 0:
            dof_x, dof_y = 0.0, 0.0
        elif i == 1:
            dof_x, dof_y = 1.0, 0.0
        elif i == 2:
            dof_x, dof_y = 1.0, 1.0
        elif i == 3:
            dof_x, dof_y = 0.0, 1.0
        elif i < 4 + (order - 1):  # x edges at y=0
            dof_x = (i - 3) * (1.0/order)
            dof_y = 0.0
        elif i < 4 + 2 * (order - 1):  # x edges at y=1
            dof_x = (i - 3 - (order - 1)) * (1.0/order)
            dof_y = 1.0
        elif i < 4 + 3 * (order - 1):  # y edges at x=0
            dof_x = 0.0
            dof_y = (i - 3 - 2 * (order - 1)) * (1.0/order)
        elif i < 4 + 4 * (order - 1):  # y edges at x=1
            dof_x = 1.0
            dof_y = (i - 3 - 3 * (order - 1)) * (1.0/order)
        else:  # interior points
            interior_idx = i - 4 - 4 * (order - 1)
            interior_per_row = order - 1
            row = interior_idx // interior_per_row
            col = interior_idx % interior_per_row
            # Interior DOFs use coordinates from edge DOFs (not corners)
            dof_x = (col + 1) * (1.0/order)
            dof_y = (row + 1) * (1.0/order)
        
        # Mark DOF points
        ax.scatter(dof_x, dof_y, 1.0, color='red', s=100, marker='o', 
                  edgecolors='black', linewidth=2, label='DOF (z=1)')
        ax.scatter(dof_x, dof_y, 0.0, color='red', s=100, marker='o', 
                  edgecolors='black', linewidth=2, label='DOF (z=0)')
        
        # Mark all other DOF locations at z=0
        # DOF positions are at intervals of 1/order
        dof_positions = []
        for a in range(order + 1):
            for b in range(order + 1):
                xi = a / order
                yi = b / order
                dof_positions.append((xi, yi))
        
        # Plot all DOF positions at z=0 (except the active one)
        for pos_x, pos_y in dof_positions:
            if not (np.isclose(pos_x, dof_x, atol=1e-2) and np.isclose(pos_y, dof_y, atol=1e-2)):
                ax.scatter(pos_x, pos_y, 0.0, color='gray', s=50, marker='o', 
                          edgecolors='black', linewidth=1, alpha=0.7)
        
        ax.set_xlabel('x')
        ax.set_ylabel('y')
        ax.set_zlabel('$b$ value')
        ax.set_title(f'$b^{{{i}}}(x,y)$')
        ax.view_init(elev=30, azim=-60)
    
    # Hide unused subplots
    for i in range(n_funcs, len(axes)):
        axes[i].set_visible(False)
    
    plt.tight_layout()
    
    # Save plot
    output_file = f'2D_lagrange_basis_order_{order}_plot.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved: {output_file}")

def plot_combined_2d_basis_functions(csv_file, order):
    """Plot all 2D basis functions in a single 3D plot."""
    # Read CSV data
    data = pd.read_csv(csv_file)
    
    # Get coordinates and basis function columns (all columns except x, y)
    x = data['x'].values
    y = data['y'].values
    basis_cols = [col for col in data.columns if col not in ['x', 'y']]
    
    # Determine grid size
    unique_x = np.unique(x)
    unique_y = np.unique(y)
    nx, ny = len(unique_x), len(unique_y)
    
    # Reshape coordinates to grid
    X = x.reshape(ny, nx)
    Y = y.reshape(ny, nx)
    
    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_subplot(111, projection='3d')
    
    # Define colors
    if len(basis_cols) <= 10:
        colors = plt.cm.tab10(np.linspace(0, 1, len(basis_cols)))
    else:
        colors = plt.cm.tab20(np.linspace(0, 1, len(basis_cols)))
    
    for i, col in enumerate(basis_cols):
        z_vals = data[col].values.reshape(ny, nx)
        
        # Create wireframe plot for each basis function
        ax.plot_wireframe(X, Y, z_vals, color=colors[i], alpha=0.8, linewidth=1.5, 
                         label=f'$b^{{{i}}}$')
        
        # Find peak location for verification
        max_idx = np.argmax(z_vals)
        max_row, max_col = np.unravel_index(max_idx, z_vals.shape)
        peak_x = X[max_row, max_col]
        peak_y = Y[max_row, max_col]
        # Place DOF at correct position based on 2D numbering
        if i == 0:
            dof_x, dof_y = 0.0, 0.0
        elif i == 1:
            dof_x, dof_y = 1.0, 0.0
        elif i == 2:
            dof_x, dof_y = 1.0, 1.0
        elif i == 3:
            dof_x, dof_y = 0.0, 1.0
        elif i < 4 + (order - 1):  # x edges at y=0
            dof_x = (i - 3) * (1.0/order)
            dof_y = 0.0
        elif i < 4 + 2 * (order - 1):  # x edges at y=1
            dof_x = (i - 3 - (order - 1)) * (1.0/order)
            dof_y = 1.0
        elif i < 4 + 3 * (order - 1):  # y edges at x=0
            dof_x = 0.0
            dof_y = (i - 3 - 2 * (order - 1)) * (1.0/order)
        elif i < 4 + 4 * (order - 1):  # y edges at x=1
            dof_x = 1.0
            dof_y = (i - 3 - 3 * (order - 1)) * (1.0/order)
        else:  # interior points
            interior_idx = i - 4 - 4 * (order - 1)
            interior_per_row = order - 1
            row = interior_idx // interior_per_row
            col = interior_idx % interior_per_row
            # Interior DOFs combine x-coords from x-edges and y-coords from y-edges
            dof_x = (col + 1) * (1.0/order)
            dof_y = (row + 1) * (1.0/order)
        
        # Mark DOF points
        ax.scatter(dof_x, dof_y, 1.0, color=colors[i], s=100, marker='o', 
                  edgecolors='black', linewidth=2)
        ax.scatter(dof_x, dof_y, 0.0, color=colors[i], s=100, marker='o', 
                  edgecolors='black', linewidth=2)
    
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('Basis Function Value')
    ax.set_title(f'2D Lagrange Basis Functions (Order {order}) - Combined View')
    ax.legend()
    ax.view_init(elev=30, azim=-60)
    
    plt.tight_layout()
    
    # Save plot
    output_file = f'2D_lagrange_basis_order_{order}_combined_plot.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved: {output_file}")

def main():
    """Main function to process all CSV files."""
    # Set path to CSV files
    csv_path = "/home/annah/masterproject/ippl/build/test/FEM"
    
    # Process 1D files
    for order in range(1, 5):
        csv_file = os.path.join(csv_path, f"1D_lagrange_local_basis_order{order}.csv")
        if os.path.exists(csv_file):
            print(f"Processing {csv_file}...")
            plot_1d_basis_functions(csv_file, order)
    
    # Process 2D files
    for order in range(1, 5):  # Process all orders 1-4 for 2D
        csv_file = os.path.join(csv_path, f"2D_lagrange_local_basis_order{order}.csv")
        if os.path.exists(csv_file):
            print(f"Processing {csv_file}...")
            plot_2d_basis_functions(csv_file, order)
            plot_combined_2d_basis_functions(csv_file, order)

if __name__ == "__main__":
    main()